#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

usage() {
	cat >&2 <<'EOF'
Usage: just/license/scripts/generate-attributions.sh [--check]

Generate ATTRIBUTIONS.md from a dedicated locked uv environment. The isolated
environment prevents stale packages in the normal development venv from leaking
into the attribution file.

Options:
  --check  Fail if ATTRIBUTIONS.md is stale
  -h, --help
EOF
}

check=0
while [[ $# -gt 0 ]]; do
	case "$1" in
	--check)
		check=1
		shift
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		usage
		exit 1
		;;
	esac
done

repo="$(git rev-parse --show-toplevel)"
work_dir="${repo}/tmp/legal-attributions"
venv_dir="${work_dir}/.venv"
body="${work_dir}/ATTRIBUTIONS.body.md"
generated="${work_dir}/ATTRIBUTIONS.md"
mkdir -p "${work_dir}"

UV_PROJECT_ENVIRONMENT="${venv_dir}" \
	uv run --frozen --no-dev --group legal --extra build \
	pip-licenses \
	--from=mixed \
	--format=plain-vertical \
	--with-license-file \
	--no-license-path \
	--output-file "${body}"
awk '
	{ lines[NR] = $0 }
	END {
		last = NR
		while (last > 0 && lines[last] == "") {
			last--
		}
		for (line_no = 1; line_no <= last; line_no++) {
			print lines[line_no]
		}
	}
' "${body}" >"${body}.trimmed"
mv "${body}.trimmed" "${body}"

{
	printf '# Third-Party Attributions\n\n'
	printf 'Generated by just license::attributions from the locked root project, '
	printf 'the build extra, and the legal dependency group. Release wheels are '
	printf 'validated separately by just license::wheel-check because this repository '
	printf 'hosts third-party wheels rather than vendoring their source trees.\n\n'
	cat "${body}"
} >"${generated}"

if [[ "${check}" -eq 1 ]]; then
	diff -u ATTRIBUTIONS.md "${generated}"
	exit 0
fi

cp "${generated}" ATTRIBUTIONS.md
